---
# tasks file for ssh
- name: ssh
  block:
    - name: check play called with all hosts
      assert:
        that: ansible_play_hosts|sort == groups.all|sort
        fail_msg: ansible_play_hosts != groups.all
        success_msg: ansible_play_hosts == groups.all
      ignore_errors: yes
      run_once: True
      connection: local

    - name: ssh_config
      become: no
      template:
        src: ssh_config.j2
        dest: ~/.ssh/config
        mode: preserve
#      run_once: True
#      connection: local

    - name: copy private user_key_file
      become: no
      copy:
        dest: ~/.ssh/id_rsa
        src: ~/.ssh/id_rsa
        mode: 600
      when: ansible_distribution != 'MacOSX'
  when: ansible_play_hosts|sort == groups.all|sort
  tags:
    - always
    - base_ssh
